FPTJob_1670/FPTJob_1670/Controllers/AccountsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FPTJob_1670.Controllers
{
    public class AccountsController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        public AccountsController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public async Task<IActionResult> Index()
        {
            var accounts = await _userManager.Users.ToListAsync();
            var userRoles = new Dictionary<string, string>();

            foreach (var user in accounts)
            {
                var roles = await _userManager.GetRolesAsync(user);
                userRoles.Add(user.Id, string.Join(", ", roles));
            }

            ViewBag.UserRoles = userRoles;

            return View(accounts);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]  
        public async Task<IActionResult> Create(IdentityRole model)
        {
            return View();

        }

        public async Task<IActionResult> LockAccount(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                await _userManager.SetLockoutEndDateAsync(user, DateTimeOffset.MaxValue);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteAccount(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }

            public async Task<IActionResult> UnlockAccount(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                await _userManager.SetLockoutEndDateAsync(user, null);
            }
            return RedirectToAction("Index");
        }
    }
}

FPTJob_1670/FPTJob_1670/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FPTJob_1670.Data;
using FPTJob_1670.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.SignalR;
using FPTJob_1670.Settings;
using Microsoft.JSInterop.Implementation;

namespace FPTJob_1670.Controllers
{
    public class JobsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IWebHostEnvironment webHostEnvironment;

        private readonly IHubContext<NotificationHub> _notificationHub;

        private readonly UserManager<IdentityUser> _userManager;
        public JobsController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment, IHubContext<NotificationHub> notificationHub, UserManager<IdentityUser> userManager)
        {
            _context = context;
            webHostEnvironment = hostEnvironment;
            _notificationHub = notificationHub;
            _userManager = userManager;
        }

        [Authorize(Roles = "Employer")]
        // GET: Jobs
        public async Task<IActionResult> Index()
        {
            var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var jobs = await _context.Job
                           .Where(j => j.Employer.EmployerId == currentUserId)
                           .Include(a => a.Employer) 
                           .ToListAsync();

            return View(jobs);
        }

        // GET: Jobs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Job == null)
            {
                return NotFound();
            }

            var job = await _context.Job
                .Include(j => j.Employer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }


        [Authorize(Roles = "Employer")]
        // GET: Jobs/Create
        public IActionResult Create()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewData["Employer_id"] = new SelectList(_context.Employer.Where(u => u.EmployerId == userId), "Id", "Name");
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Title,Application_Deadline,Salary,Employer_id,ProfileImage")] Job job)
        {
            if (ModelState.IsValid)
            {
                if (job.ProfileImage != null)
                {
                    string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + job.ProfileImage.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await job.ProfileImage.CopyToAsync(fileStream);
                    }
                    job.Image = "/images/" + uniqueFileName;
                }

                job.statusJobs = "Not Confirmed";

                _context.Add(job);
                await _context.SaveChangesAsync();

                var admins = await _userManager.GetUsersInRoleAsync("Admin");
                foreach (var admin in admins)
                {
                    await CreateNotification(admin.Id, "A new job want to accepted");
                }

                return RedirectToAction(nameof(Index));
            }
            ViewData["Employer_id"] = new SelectList(_context.Employer, "Id", "Name", job.Employer_id);
            return View(job);
        }



        public async Task CreateNotification(string userId, string message)
        {
            var notification = new Notification
            {
                UserId = userId,
                Message = message,
            };

            _context.Notification.Add(notification);
            await _context.SaveChangesAsync();

            await _notificationHub.Clients.User(userId).SendAsync("ReceiveNotification", message);
        }

        public async Task<int> GetUnreadNotificationCount()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var unreadCount=await _context.Notification.Where(n=>n.UserId== userId && !n.IsRead).CountAsync();
            return unreadCount;
        }

        [Authorize(Roles = "Employer")]
        // GET: Jobs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Job == null)
            {
                return NotFound();
            }

            var job = await _context.Job.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }
            ViewData["Employer_id"] = new SelectList(_context.Employer, "Id", "Name", job.Employer_id);
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Title,Application_Deadline,Salary,Employer_id,ProfileImage")] Job job)
        {
            if (id != job.Id)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {

                try
                {
                    var jobUpdate = await _context.Job.FindAsync(id);
                    if (jobUpdate == null)
                    {
                        return NotFound();
                    }

                    // Copy các thông tin mới từ jobSeeker vào jobSeekerToUpdate
                    jobUpdate.Name = job.Name;
                    //jobSeekerToUpdate.Email = jobSeeker.Email;
                    jobUpdate.Description = job.Description;
                    jobUpdate.Title = job.Title;
                    jobUpdate.Application_Deadline = job.Application_Deadline;
                    jobUpdate.Salary = job.Salary;

                    jobUpdate.statusJobs = jobUpdate.statusJobs;

                    // Xử lý tải lên ảnh mới và cập nhật đường dẫn ảnh mới
                    if (job.ProfileImage != null)
                    {
                        string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                        string uniqueFileName = Guid.NewGuid().ToString() + "_" + job.ProfileImage.FileName;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await job.ProfileImage.CopyToAsync(fileStream);
                        }
                        jobUpdate.Image = "/images/" + uniqueFileName;
                    }

                    _context.Update(jobUpdate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobExists(job.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
           ViewData["Employer_id"] = new SelectList(_context.Employer, "Id", "Name", job.Employer_id);
            return View(job);
        }


        [Authorize(Roles = "Employer")]
        // GET: Jobs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Job == null)
            {
                return NotFound();
            }

            var job = await _context.Job
                .Include(j => j.Employer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Job == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Job'  is null.");
            }
            var job = await _context.Job.FindAsync(id);
            if (job != null)
            {
                _context.Job.Remove(job);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JobExists(int id)
        {
            return (_context.Job?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        [HttpPost]
        public async Task<IActionResult> AcceptJob (int id)
        {
            var job = await _context.Job.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }

            job.statusJobs = "Accepted";
            _context.Job.Update(job);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]

FPTJob_1670/FPTJob_1670/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace FPTJob_1670.Controllers
{
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model)
        {
            if (!await _roleManager.RoleExistsAsync(model.Name))
            {
                await _roleManager.CreateAsync(new IdentityRole(model.Name));
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, IdentityRole model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(id);
                    if (role != null)
                    {
                        role.Name = model.Name;
                        var result = await _roleManager.UpdateAsync(role);
                        if (result.Succeeded)
                        {
                            return RedirectToAction(nameof(Index));
                        }
                    }
                    return View(model);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
            }
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }


        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(DeleteSuccess));
                }
            }
            return NotFound();
        }

        public IActionResult DeleteSuccess()
        {
            return View();
        }


    }
}

FPTJob_1670/FPTJob_1670/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin Dashboard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- Add other CSS files if needed -->
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">Admin Dashboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Roles" asp-action="Index">Role</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Accounts" asp-action="Index">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Back Home</a>
                    </li>
                    <form asp-action="Index" asp-controller="Notifications" method="post">
                        <button type="submit" class="btn btn-danger">Notification</button>
                    </form>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-3">
        @RenderBody()
    </div>

    <!-- Add scripts if needed -->
</body>
</html>

FPTJob_1670/FPTJob_1670/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FPTJob_1670</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FPTJob_1670.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FPTJob_1670</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <form asp-controller="Home" asp-action="Search" method="get">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Search by name" name="searchString" value="@ViewData["CurrentFilter"]">
                        <button class="btn btn-outline-secondary" type="submit">Search</button>
                    </div>
                </form>
                       <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                                @if (User.IsInRole("Seeker"))
                                {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Seekers" asp-action="Index">Seeker</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Applications" asp-action="Index">Application</a>
                        </li>
                                <li>
                                    <form asp-action="Index" asp-controller="Notifications" method="post">
                                        <button type="submit" class="btn btn-danger">Notification</button>
                                    </form>

                                </li>
                                }
                                @if (User.IsInRole("Employer"))
                                {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employers" asp-action="Index">Employer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jobs" asp-action="Index">Jobs</a>
                        </li>
                         <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Applications" asp-action="EmployerManage">Application</a>
                        </li>
                        <li>
                                    <form asp-action="Index" asp-controller="Notifications" method="post">
                                        <button type="submit" class="btn btn-danger">Notification</button>
                                    </form>

                        </li>
                                
                                }
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FPTJob_1670 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>